### ISSUE TITLE
Plugin doesn't support Rabbit 3.7.x series

### ISSUE THREAD

**Issue by zaharcelac** [Ayanda-D/rabbitmq-queue-master-balancer#1]
Thank you for creating the pluging I was waiting for. But my first lab setup fails. Hope you can advise.

My Lab config:
- cluster of 3x rabbitmq nodes (ubuntu 16.04.3, Erlang 20.1, rabbitmq 3.7.0)
- enabled plugins: rabbitmq_management, rabbitmq_queue_master_balancer
- 7x queues with HA policy applied (all master queues hosted by node#1, all replicas hosted by node#2)

I can successfully enable rabbit_queue_master_balancer plugin and run **info()** and **load_queues()** commands.

When I try to run **report()** it fails with the following output:

`
Error:
{{{:unsupported_version, {:amqqueue, {:resource, "/", :queue, "queue-6"}, true, false, :none, [], #PID<9639.775.0>, [#PID<9226.637.0>], [#PID<9226.637.0>], [:"rabbit@rmq-2"], [vhost: "/", name: "ha", pattern: ".*", "apply-to": "queues", definition: [{"ha-mode", "exactly"}, {"ha-params", 2}, {"ha-sync-mode", "automatic"}, {"queue-master-locator", "min-masters"}], priority: 0], :undefined, [{#PID<9226.638.0>, #PID<9226.637.0>}, {#PID<9639.777.0>, #PID<9639.775.0>}], [], :live, 0, [], "/", %{user: "guest"}}}, [{:rabbit_queue_master_balancer, :get_queue_node, 1, [file: 'src/rabbit_queue_master_balancer.erl', line: 295]}, {:rabbit_queue_master_balancer, :"-make_report/0-fun-0-", 2, [file: 'src/rabbit_queue_master_balancer.erl', line: 278]}, {:lists, :foldl, 3, [file: 'lists.erl', line: 1263]}, {:rabbit_queue_master_balancer, :make_report, 0, [file: 'src/rabbit_queue_master_balancer.erl', line: 278]}, {:rabbit_queue_master_balancer, :handle_sync_event, 4, [file: 'src/rabbit_queue_master_balancer.erl', line: 113]}, {:gen_fsm, :handle_msg, 8, [file: 'gen_fsm.erl', line: 483]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}, {:gen_fsm, :sync_send_all_state_event, [:rabbit_queue_master_balancer, :"$report"]}}
`

UPD: the only time I was able to run **report()** successfully - when I have no queues in cluster

**Comment by Ayanda-D** [comment]
@zaharcelac `:unsupported_version` error indicating a compatibility issue with the new rabbit `3.7.0`. Providing a fix soon. thanks for reporting 👍
