### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by nicolasbock** [Ayanda-D/rabbitmq-queue-master-balancer#13]
Hi @Ayanda-D !

Is this project still active? I noticed that the stable branches seem to be ahead of the master branch.

Thanks!

Nick

**Comment by Ayanda-D** [comment]
@nicolasbock sorry this slipped! Yes plugin, is still active (mainly in use by our paying clients, for RabbitMQ versions 3.7.x and older). Just download latest release: https://github.com/Ayanda-D/rabbitmq-queue-master-balancer/releases 

What version are you running?

For 3.8.x, please use the new queue rebalance command: https://www.rabbitmq.com/rabbitmq-queues.8.html#Cluster
