### ISSUE TITLE
(CaseClauseError) no case clause matching: {:plugin_built_with_incompatible_erlang, 'rabbitmq_queue_master_balancer'}

### ISSUE THREAD

**Issue by theorb77** [Ayanda-D/rabbitmq-queue-master-balancer#5]
I'm trying out your plugin on RabbitMQ 3.7.3 and Erlang 19.3, and I'm getting the above. What Erlang version do I need to use this?

Thanks for building this.

**Comment by Ayanda-D** [comment]
hi @theorb77 the [v0.0.3 release](https://github.com/Ayanda-D/rabbitmq-queue-master-balancer/releases/tag/v0.0.3) was built on Erlang 20. So won't work on 19.3.

I've just uploaded a package [built on 19.3 here](https://drive.google.com/file/d/18SkjiHGi0ltQHZBFsKuOBW5Wgu7MbtUZ/view?usp=sharing), which you can use. Cheers 👍
