### ISSUE TITLE
Make inter-synchronization verification checks more resistant when balancing queues of high magnitude message depth

### ISSUE THREAD

**Issue by bwmills** [Ayanda-D/rabbitmq-queue-master-balancer#7]
Hi @Ayanda-D - re-tested the plugin in a non-production environment for evaluation.

Unfortunately we ran into the same issue I initially reported here: https://github.com/Ayanda-D/rabbitmq-queue-master-balancer/issues/6

Our setup was the same as described in the previous issue. Here are a few quick notes:

### Plugin

* Version: `0.0.4`

### RabbitMQ Config

* RabbitMQ version: `3.7.4`
* Erlang version: `20.3`
* Cluster size: `3 nodes`

### Notes

(1) The plugin did succeed once in balancing 145 queues with very little data and no consumers.

(2) The plugin crashed in the same setup, where the only difference was that we had 9 queues with 100,000 messages each (ready - not yet consumed). The crash occurred consistently (three times). The log output was:

```
E0000 2019-02-22T19:47:39.082Z 0000 rabbitmq] Queue Master Balancer synchronisation error. Queue: <<"my-queue">>, Reason: {badmatch,true}
E0000 2019-02-22T19:47:39.082Z 0000 rabbitmq] ** State machine rabbit_queue_master_balancer terminating
** Last event in was '$balance_queues'
** When State == balancing_queues
**      Data  == {state,<0.21381.2>,balancing_queues,152,140,162,14,5,3000,50,1550864853665}
** Reason for termination =
** {{badmatch,{error,{badmatch,true}}},[{rabbit_queue_master_balancer,balancing_queues,2,[{file,"src/rabbit_queue_master_balancer.erl"},{line,198}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
E0000 2019-02-22T19:47:39.082Z 0000 rabbitmq] CRASH REPORT Process rabbit_queue_master_balancer with 0 neighbours exited with reason: no match of right hand value {error,{badmatch,true}} in rabbit_queue_master_balancer:balancing_queues/2 line 198 in gen_fsm:terminate/7
E0000 2019-02-22T19:47:39.082Z 0000 rabbitmq] Supervisor rabbit_queue_master_balancer_sup had child rabbit_queue_master_balancer started with rabbit_queue_master_balancer:start_link() at <0.21382.2> exit with reason no match of right hand value {error,{badmatch,true}} in rabbit_queue_master_balancer:balancing_queues/2 line 198 in context child_terminated
```

(3) I'll have a closer look at the specific queue mentioned in the error and will follow-up if anything useful is discovered.

**Comment by bwmills** [comment]
@Ayanda-D - is it possible to get an update on this?

**Comment by Ayanda-D** [comment]
@bwmills version `0.0.4` is more defensive in verifying that balanced queues are precisely/correctly synchronized per balancing operation. It seems like the high rate of synchronization verification checks per queue during the internal state machine's balancing phase is affecting the temporary process (asynchronous - so it doesn't affect anything else) carrying out this procedure. This is directly proportional to the queue's message depth (100k in your case, i.e. the more the messages, the longer/more the verification checks will execute). This ensures consistency, but should be more controllable for different cases when message counts get large. I'm working on next version to address this (we have a time window, so you can expect it soon). Thanks again for testing! 👋

**Comment by bwmills** [comment]
Thanks @Ayanda-D for that answer - much appreciated.

Again this plugin is exactly what we need and would help greatly in reducing risk when performing a rolling update of our production RabbitMQ cluster in Kubernetes. Will gladly test again with `0.0.5`.

**Comment by bwmills** [comment]
Hi @Ayanda-D - any updates on the `0.0.5` release?

**Comment by Ayanda-D** [comment]
@bwmills yes, just released - find the artefacts and release notes here: https://github.com/Ayanda-D/rabbitmq-queue-master-balancer/releases/tag/v0.0.5 - please try it out and give (your valuable) feedback. Thanks again so much! 👍

**Comment by bwmills** [comment]
@Ayanda-D - great and many thanks!
Will test soon and follow-up.

**Comment by Ayanda-D** [comment]
Fixed in https://github.com/Ayanda-D/rabbitmq-queue-master-balancer/commit/c958e9e05e001269275609db9faaa912b9400e08. If anything of this nature manifests for higher workloads on queues, we'll handle separately. This is also tested and validated in the [automated tests](https://github.com/Ayanda-D/rabbitmq-queue-master-balancer#testing). Thanks again! 👍
