### ISSUE TITLE
Increase default internal FSM call timeouts

### ISSUE THREAD

**Issue by 01045972746** [Ayanda-D/rabbitmq-queue-master-balancer#8]
When any queue has message, it has been returned like this.
Test Message is {"test": "test"}.
I have published on rabbitMQ management admin.

```bash
$ sudo ./rabbitmqctl eval 'rabbit_queue_master_balancer:report().'

** (Protocol.UndefinedError) protocol String.Chars not implemented for {:gen_fsm, :sync_send_all_state_event, [:rabbit_queue_master_balancer, :"$report", 5000]}. This protocol is implemented for: Atom, BitString, Date, DateTime, Float, Integer, List, NaiveDateTime, Time, URI, Version.Requirement, Version, Atom, BitString, Date, DateTime, Float, Integer, List, NaiveDateTime, Time, URI, Version.Requirement, Version
    (elixir) /Users/jose/OSS/elixir/lib/elixir/lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) /Users/jose/OSS/elixir/lib/elixir/lib/string/chars.ex:22: String.Chars.to_string/1
    (rabbitmqctl) lib/rabbitmqctl.ex:418: RabbitMQCtl.format_error/3
    (rabbitmqctl) lib/rabbitmqctl.ex:45: RabbitMQCtl.main/1
    (elixir) lib/kernel/cli.ex:105: anonymous fn/3 in Kernel.CLI.exec_fun/2

```

![image](https://user-images.githubusercontent.com/20312544/56779873-ef4f5100-6817-11e9-9440-3184d5b97659.png)

**Comment by Ayanda-D** [comment]
@01045972746 your report command call is timing out - taking longer than the default timeout of [5 seconds](https://github.com/Ayanda-D/rabbitmq-queue-master-balancer/blob/v0.0.4/src/rabbit_queue_master_balancer.erl#L62) to return the report. From Rabbit `3.7.x`, the CLI, `rabbitmqctl` is now an [Elixir implementation](https://github.com/rabbitmq/rabbitmq-cli) and currently, plugin implementation, when there's an error returned (as in your case) native Erlang primitives aren't being formatted correctly. Work-around, increase the timeout from 5 seconds, to e.g 10 seconds, or more, as follows:

`$ sudo ./rabbitmqctl eval 'rabbit_queue_master_balancer:report(10000).'`

You shouldn't see this error. I'll improve the error handling for any returned errors in the next version. 

Thanks for reporting this! 🤠

**Comment by Ayanda-D** [comment]
Fixed in https://github.com/Ayanda-D/rabbitmq-queue-master-balancer/commit/5b4a06ea2cdbb6e515adcd7f82049a8b73237229
